<?php /* @var Magento\Sales\Block\Adminhtml\Order\View $block */
if (!empty($block->getOrder()->getTaskOrderComments())) {
    ?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */ __('Order Comments') ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item">
                <div class="admin__page-section-item-content">
                    <div class="order-payment-method-title Task-order-comments-box" id="order-comments-label-div">
                    <span><?= $block->escapeHtml(nl2br($block->getOrder()->getTaskOrderComments())); ?></span>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <?php
}
?>
